from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_text.setGeometry(QtCore.QRect(10, 0, 431, 91))
        self.result_text.setObjectName("result_text")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 100, 431, 398))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plus_button = QtWidgets.QPushButton(self.widget)
        self.plus_button.setMinimumSize(QtCore.QSize(81, 61))
        self.plus_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.plus_button.setObjectName("plus_button")
        self.gridLayout.addWidget(self.plus_button, 4, 3, 1, 1)
        self.square_root_button = QtWidgets.QPushButton(self.widget)
        self.square_root_button.setMinimumSize(QtCore.QSize(81, 61))
        self.square_root_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.square_root_button.setObjectName("square_root_button")
        self.gridLayout.addWidget(self.square_root_button, 0, 1, 1, 1)
        self.multiplication_button = QtWidgets.QPushButton(self.widget)
        self.multiplication_button.setMinimumSize(QtCore.QSize(81, 61))
        self.multiplication_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.multiplication_button.setObjectName("multiplication_button")
        self.gridLayout.addWidget(self.multiplication_button, 2, 3, 1, 1)
        self.percent_button = QtWidgets.QPushButton(self.widget)
        self.percent_button.setMinimumSize(QtCore.QSize(81, 61))
        self.percent_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.percent_button.setObjectName("percent_button")
        self.gridLayout.addWidget(self.percent_button, 0, 0, 1, 1)
        self.square_button = QtWidgets.QPushButton(self.widget)
        self.square_button.setMinimumSize(QtCore.QSize(81, 61))
        self.square_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.square_button.setObjectName("square_boot")
        self.gridLayout.addWidget(self.square_button, 0, 2, 1, 1)
        self.eight_button = QtWidgets.QPushButton(self.widget)
        self.eight_button.setMinimumSize(QtCore.QSize(81, 61))
        self.eight_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.eight_button.setObjectName("eight_button")
        self.gridLayout.addWidget(self.eight_button, 2, 1, 1, 1)
        self.comma_button = QtWidgets.QPushButton(self.widget)
        self.comma_button.setMinimumSize(QtCore.QSize(81, 61))
        self.comma_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.comma_button.setObjectName("comma_button")
        self.gridLayout.addWidget(self.comma_button, 5, 2, 1, 1)
        self.four_button = QtWidgets.QPushButton(self.widget)
        self.four_button.setMinimumSize(QtCore.QSize(81, 61))
        self.four_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.four_button.setObjectName("four_button")
        self.gridLayout.addWidget(self.four_button, 3, 0, 1, 1)
        self.equally_button = QtWidgets.QPushButton(self.widget)
        self.equally_button.setMinimumSize(QtCore.QSize(81, 61))
        self.equally_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.equally_button.setObjectName("equally_button")
        self.gridLayout.addWidget(self.equally_button, 5, 3, 1, 1)
        self.ce_button = QtWidgets.QPushButton(self.widget)
        self.ce_button.setMinimumSize(QtCore.QSize(81, 61))
        self.ce_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.ce_button.setObjectName("ce_button")
        self.gridLayout.addWidget(self.ce_button, 1, 1, 1, 1)
        self.plus_minus_button = QtWidgets.QPushButton(self.widget)
        self.plus_minus_button.setMinimumSize(QtCore.QSize(81, 61))
        self.plus_minus_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.plus_minus_button.setObjectName("plus_minus_button")
        self.gridLayout.addWidget(self.plus_minus_button, 5, 0, 1, 1)
        self.minus_button = QtWidgets.QPushButton(self.widget)
        self.minus_button.setMinimumSize(QtCore.QSize(81, 61))
        self.minus_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.minus_button.setObjectName("minus_button")
        self.gridLayout.addWidget(self.minus_button, 3, 3, 1, 1)
        self.zero_button = QtWidgets.QPushButton(self.widget)
        self.zero_button.setMinimumSize(QtCore.QSize(81, 61))
        self.zero_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.zero_button.setObjectName("zero_button")
        self.gridLayout.addWidget(self.zero_button, 5, 1, 1, 1)
        self.hex_button = QtWidgets.QPushButton(self.widget)
        self.hex_button.setMinimumSize(QtCore.QSize(81, 61))
        self.hex_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.hex_button.setObjectName("hex_button")
        self.gridLayout.addWidget(self.hex_button, 1, 0, 1, 1)
        self.nine_button = QtWidgets.QPushButton(self.widget)
        self.nine_button.setMinimumSize(QtCore.QSize(81, 61))
        self.nine_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.nine_button.setObjectName("nine_button")
        self.gridLayout.addWidget(self.nine_button, 2, 2, 1, 1)
        self.seven_button = QtWidgets.QPushButton(self.widget)
        self.seven_button.setMinimumSize(QtCore.QSize(81, 61))
        self.seven_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.seven_button.setObjectName("seven_button")
        self.gridLayout.addWidget(self.seven_button, 2, 0, 1, 1)
        self.six_button = QtWidgets.QPushButton(self.widget)
        self.six_button.setMinimumSize(QtCore.QSize(81, 61))
        self.six_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.six_button.setObjectName("six_button")
        self.gridLayout.addWidget(self.six_button, 3, 2, 1, 1)
        self.bin_button = QtWidgets.QPushButton(self.widget)
        self.bin_button.setMinimumSize(QtCore.QSize(81, 61))
        self.bin_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.bin_button.setObjectName("bin_button")
        self.gridLayout.addWidget(self.bin_button, 1, 2, 1, 1)
        self.one_button = QtWidgets.QPushButton(self.widget)
        self.one_button.setMinimumSize(QtCore.QSize(81, 61))
        self.one_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.one_button.setObjectName("one_button")
        self.gridLayout.addWidget(self.one_button, 4, 0, 1, 1)
        self.opposite_button = QtWidgets.QPushButton(self.widget)
        self.opposite_button.setMinimumSize(QtCore.QSize(81, 61))
        self.opposite_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.opposite_button.setObjectName("opposite_button")
        self.gridLayout.addWidget(self.opposite_button, 0, 3, 1, 1)
        self.three_button = QtWidgets.QPushButton(self.widget)
        self.three_button.setMinimumSize(QtCore.QSize(81, 61))
        self.three_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.three_button.setObjectName("three_button")
        self.gridLayout.addWidget(self.three_button, 4, 2, 1, 1)
        self.division_button = QtWidgets.QPushButton(self.widget)
        self.division_button.setMinimumSize(QtCore.QSize(81, 61))
        self.division_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.division_button.setObjectName("division_button")
        self.gridLayout.addWidget(self.division_button, 1, 3, 1, 1)
        self.five_button = QtWidgets.QPushButton(self.widget)
        self.five_button.setMinimumSize(QtCore.QSize(81, 61))
        self.five_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.five_button.setObjectName("five_button")
        self.gridLayout.addWidget(self.five_button, 3, 1, 1, 1)
        self.two_button = QtWidgets.QPushButton(self.widget)
        self.two_button.setMinimumSize(QtCore.QSize(81, 61))
        self.two_button.setStyleSheet("font: 22pt \"Ubuntu\";")
        self.two_button.setObjectName("two_button")
        self.gridLayout.addWidget(self.two_button, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.square_root_button.setText(_translate("MainWindow", "√"))
        self.multiplication_button.setText(_translate("MainWindow", "*"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.square_button.setText(_translate("MainWindow", " X²"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.comma_button.setText(_translate("MainWindow", ","))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.equally_button.setText(_translate("MainWindow", "="))
        self.bin_button.setText(_translate("MainWindow", "BIN"))
        self.plus_minus_button.setText(_translate("MainWindow", "+-"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.hex_button.setText(_translate("MainWindow", "HEX"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.ce_button.setText(_translate("MainWindow", "CE"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.opposite_button.setText(_translate("MainWindow", "1/X"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.division_button.setText(_translate("MainWindow", "÷"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.two_button.setText(_translate("MainWindow", "2"))
