deff('y=f(x)','y=2*x^3 - 7*x');
x0=-4;
z=numderivative(f, x0);
mprintf("Значение производной в точке x0: %f ",z);
b=f(x0)-z*x0;
deff('g=kas(x)', 'g=z*x+b');
xgraph=-7:0.1:1;
fgraph=f(xgraph);
kasgraph=kas(xgraph);
plot(xgraph,fgraph,xgraph,kasgraph);
xgrid(100);
legend ("y=f(x)", "y=z(x, x0)");
